version: "3.3"

services:
  database:
    container_name: agenda_evento
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=devcontratado
      - POSTGRES_PASSWORD=passdevcontratado
    ports:
      - 5439:5432